In [3]:
from sklearn.feature_extraction.text import CountVectorizer
d1="I love programming"
d2="programming is intresting"
d3="I love pizza very very much"
documents=[d1,d2,d3]
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(documents)
print(vectorizer.vocabulary_)
print(X.toarray())

{'love': 2, 'programming': 5, 'is': 1, 'intresting': 0, 'pizza': 4, 'very': 6, 'much': 3}
[[0 0 1 0 0 1 0]
 [1 1 0 0 0 1 0]
 [0 0 1 1 1 0 2]]


In [4]:
import pandas as pd
df=pd.read_csv('newsgroups_train.csv')
print(df.iloc[0:20])

                                                 text  target       category
0   From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1   From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2   From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3   From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4   From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space
5   From: dietz@cs.rochester.edu (Paul Dietz)\nSub...       2      sci.space
6   From: cobb@alexia.lis.uiuc.edu (Mike Cobb)\nSu...       0    alt.atheism
7   From: edm@twisto.compaq.com (Ed McCreary)\nSub...       0    alt.atheism
8   From: dgraham@bmers30.bnr.ca (Douglas Graham)\...       0    alt.atheism
9   From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...       0    alt.atheism
10  From: darice@yoyo.cc.monash.edu.au (Fred Rice)...       0    alt.atheism
11  From: mikec@sail.LABS.TEK.COM (Micheal Cranfor...       1  comp.graphics

In [5]:
import pandas as pd
f=pd.read_csv('newsgroups_train.csv')
f.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1657 entries, 0 to 1656
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   text      1657 non-null   object
 1   target    1657 non-null   int64 
 2   category  1657 non-null   object
dtypes: int64(1), object(2)
memory usage: 39.0+ KB


In [6]:
#load 20 
df=pd.read_csv('newsgroups_test.csv')
print(df.iloc[0:20])
df.info()

                                                 text  target       category
0   From: mccall@mksol.dseg.ti.com (fred j mccall ...       2      sci.space
1   From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...       1  comp.graphics
2   From: lioness@maple.circa.ufl.edu\nSubject: Te...       1  comp.graphics
3   From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...       1  comp.graphics
4   From: Ad-Robot@bobsbox.rent.com (Robotic Posti...       1  comp.graphics
5   From: lee@hobbes.cs.umass.edu (Peter Lee)\nSub...       1  comp.graphics
6   From: gck@aero.org (Gregory C. Kozlowski)\nSub...       0    alt.atheism
7   From: PHARABOD@FRCPN11.IN2P3.FR\nSubject: Fran...       2      sci.space
8   From: wingo%cspara.decnet@Fedex.Msfc.Nasa.Gov\...       2      sci.space
9   From: nsmca@aurora.alaska.edu\nSubject: Combo ...       2      sci.space
10  From: gcdcrgm@state.systems.sa.gov.au\nSubject...       1  comp.graphics
11  From: aaron@minster.york.ac.uk\nSubject: Re: D...       0    alt.atheism

In [7]:
#print all target labels
print(df['target'].unique())

[2 1 0]


In [8]:
#6.prepare subset of categories alt.athhesum com.graphics sci.space
from sklearn.datasets import fetch_20newsgroups

# Define categories to extract
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load subset of the dataset
newsgroups_subset = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print number of documents per category
print(f"Total documents: {len(newsgroups_subset.data)}")
print(f"Target labels: {set(newsgroups_subset.target)}")  # Numeric labels
print(f"Target names: {newsgroups_subset.target_names}")  # Category names


Total documents: 1657
Target labels: {np.int64(0), np.int64(1), np.int64(2)}
Target names: ['alt.atheism', 'comp.graphics', 'sci.space']


In [9]:
#7.load 20 news group train subset with three categroies lt.athesim ; comp.graphic
from sklearn.datasets import fetch_20newsgroups

# Define categories to extract
categories = ['alt.atheism', 'comp.graphics', 'sci.space']  # Modify if needed

# Load the dataset (training subset)
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print dataset details
print(f"Total documents: {len(newsgroups_train.data)}")
print(f"Target labels: {set(newsgroups_train.target)}")  # Numeric labels
print(f"Target names: {newsgroups_train.target_names}")  # Category names


Total documents: 1657
Target labels: {np.int64(0), np.int64(1), np.int64(2)}
Target names: ['alt.atheism', 'comp.graphics', 'sci.space']


In [10]:
#8.load 20 news group test subset categories alt.athesim comp.graphics

from sklearn.datasets import fetch_20newsgroups

# Define categories to extract
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the dataset (test subset)
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print dataset details
print(f"Total documents: {len(newsgroups_test.data)}")
print(f"Target labels: {set(newsgroups_test.target)}")  # Numeric labels
print(f"Target names: {newsgroups_test.target_names}")  # Category names


Total documents: 1102
Target labels: {np.int64(0), np.int64(1), np.int64(2)}
Target names: ['alt.atheism', 'comp.graphics', 'sci.space']


In [11]:
#9.print new training set target names(labels)
# Print target names (labels)
print("Target Names (Labels):")
print(newsgroups_train.target_names)

Target Names (Labels):
['alt.atheism', 'comp.graphics', 'sci.space']


In [12]:
#10.print new training data of 5th article
print(newsgroups_train.data[4])


I don't think you're going to be able to see the differences from a sphere
unless they are greatly exaggerated.  Even the equatorial bulge is only
about 1 part in 300 -- you'd never notice a 1mm error in a 30cm globe --
and the other deviations from spherical shape are much smaller.


In [13]:
#11.print shape of data and targets
from sklearn.datasets import fetch_20newsgroups

# Define categories to extract
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the dataset (training subset)
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print the shape of data and targets
print("Number of documents (data shape):", len(newsgroups_train.data))
print("Number of target labels:", len(newsgroups_train.target))  

Number of documents (data shape): 1657
Number of target labels: 1657


In [14]:
#12.print training set filenames

In [15]:
#13.by using Countvectorizer train data ito numerical format considering
from sklearn.feature_extraction.text import CountVectorizer
mf=(df.head())
vectorizer = CountVectorizer()

# Convert text data into numerical form
X = vectorizer.fit_transform(mf.text)

# Display the vocabulary (words mapped to indices)
print("Vocabulary:", vectorizer.vocabulary_)

# Display the transformed data as an array
print("Numerical representation:\n", X.toarray())

Vocabulary: {'from': 186, 'mccall': 269, 'mksol': 283, 'dseg': 153, 'ti': 426, 'com': 106, 'fred': 184, '575': 20, '3539': 12, 'subject': 402, 're': 348, 'satellite': 366, 'around': 59, 'pluto': 331, 'mission': 282, 'organization': 314, 'texas': 410, 'instruments': 223, 'inc': 216, 'lines': 246, '24': 7, 'in': 215, '1993apr30': 6, '004311': 0, 'aurora': 66, 'alaska': 37, 'edu': 158, 'nsmca': 303, 'writes': 484, 'being': 78, 'wierd': 475, 'again': 36, 'so': 387, 'be': 74, 'warned': 462, 'is': 228, 'there': 419, 'plan': 327, 'to': 428, 'put': 343, 'each': 154, 'planet': 328, 'the': 415, 'solar': 389, 'system': 405, 'keep': 233, 'watch': 464, 'help': 200, 'it': 229, 'better': 80, 'ask': 63, 'questions': 344, 'before': 77, 'spout': 395, 'an': 46, 'opinion': 311, 'how': 207, 'about': 27, 'unmanned': 443, 'stay': 397, 'orbit': 313, 'and': 47, 'record': 352, 'things': 422, 'near': 292, 'on': 307, 'know': 236, 'strange': 401, 'idea': 211, 'but': 90, 'why': 474, 'not': 301, 'could': 123, 'do': 

In [16]:
#14.use bernouli NM for training  



In [18]:
#16.predict target labels for testing set
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split

# Step 1: Load the dataset (Assuming it's a CSV file with 'text' and 'label' columns)
df = pd.read_csv("newsgroups_train.csv")  # Replace with your actual dataset path
test_df = pd.read_csv("newsgroups_test.csv")  # Replace with your actual test dataset path

# Step 2: Extract features and labels
train_documents = df["text"].astype(str)  # Convert text column to string
train_labels = df["target"]  # Labels (0, 1, 2, etc.)

test_documents = test_df["text"].astype(str)  # Convert test text column to string

# Step 3: Convert text into numerical format using CountVectorizer
vectorizer = CountVectorizer(binary=True)
X_train = vectorizer.fit_transform(train_documents)
X_test = vectorizer.transform(test_documents)  # Transform test data using the same vectorizer

# Step 4: Train Bernoulli Naïve Bayes model
model = BernoulliNB()
model.fit(X_train, train_labels)

# Step 5: Predict target values for test data
predictions = model.predict(X_test)

# Step 6: Save or print predictions
test_df["predicted_label"] = predictions  # Add predictions to test dataframe
test_df.to_csv("predictions.csv", index=False)  # Save predictions to CSV
print(test_df[["text", "predicted_label"]])  # Display results


                                                   text  predicted_label
0     From: mccall@mksol.dseg.ti.com (fred j mccall ...                2
1     From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...                1
2     From: lioness@maple.circa.ufl.edu\nSubject: Te...                1
3     From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...                1
4     From: Ad-Robot@bobsbox.rent.com (Robotic Posti...                1
...                                                 ...              ...
1097  From: malek@pi.titech.ac.jp (Zidouri Abdelmale...                1
1098  From: livesey@solntze.wpd.sgi.com (Jon Livesey...                0
1099  From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...                0
1100  From: beck@irzr17.inf.tu-dresden.de (Andre Bec...                1
1101  From: 18084TM@msu.edu (Tom)\nSubject: Billboar...                2

[1102 rows x 2 columns]


In [19]:
#17.find accuracy score on test set
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score

# Step 1: Load the dataset (Assuming it's a CSV file with 'text' and 'label' columns)
df = pd.read_csv("newsgroups_train.csv")  # Replace with your actual training dataset path
test_df = pd.read_csv("newsgroups_test.csv")  # Replace with your actual test dataset path

# Step 2: Extract features and labels
train_documents = df["text"].astype(str)  # Convert text column to string
train_labels = df["target"]  # Labels (0, 1, 2, etc.)

test_documents = test_df["text"].astype(str)  # Convert test text column to string
test_labels = test_df["target"]  # True labels for accuracy calculation

# Step 3: Convert text into numerical format using CountVectorizer
vectorizer = CountVectorizer(binary=True)
X_train = vectorizer.fit_transform(train_documents)
X_test = vectorizer.transform(test_documents)  # Transform test data using the same vectorizer

# Step 4: Train Bernoulli Naïve Bayes model
model = BernoulliNB()
model.fit(X_train, train_labels)

# Step 5: Predict target values for test data
predictions = model.predict(X_test)

# Step 6: Compute Accuracy Score
accuracy = accuracy_score(test_labels, predictions)
print(f"Accuracy Score: {accuracy:.4f}")  # Print accuracy with 4 decimal places


Accuracy Score: 0.8530


In [20]:
#18.use tfidvectorizer instead of count vectorizer
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score

# Step 1: Load the dataset (Assuming it's a CSV file with 'text' and 'label' columns)
df = pd.read_csv("newsgroups_train.csv")  # Replace with your actual training dataset path
test_df = pd.read_csv("newsgroups_test.csv")  # Replace with your actual test dataset path

# Step 2: Extract features and labels
train_documents = df["text"].astype(str)  # Convert text column to string
train_labels = df["target"]  # Labels (0, 1, 2, etc.)

test_documents = test_df["text"].astype(str)  # Convert test text column to string
test_labels = test_df["target"]  # True labels for accuracy calculation

# Step 3: Convert text into numerical format using TfidfVectorizer
vectorizer = TfidfVectorizer(binary=True)  # TF-IDF representation
X_train = vectorizer.fit_transform(train_documents)
X_test = vectorizer.transform(test_documents)  # Transform test data using the same vectorizer

# Step 4: Train Bernoulli Naïve Bayes model
model = BernoulliNB()
model.fit(X_train, train_labels)

# Step 5: Predict target values for test data
predictions = model.predict(X_test)

# Step 6: Compute Accuracy Score
accuracy = accuracy_score(test_labels, predictions)
print(f"Accuracy Score: {accuracy:.4f}")  # Print accuracy with 4 decimal places


Accuracy Score: 0.8530


In [21]:
#15. By using countvectorizer convert test data into numeric format considering only
f=pd.read_csv('newsgroups_test.csv')
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

# Convert text data into numerical form
X = vectorizer.fit_transform(df.text)

# Display the vocabulary (words mapped to indices)
print("Vocabulary:", vectorizer.vocabulary_)

# Display the transformed data as an array
md=print("Numerical representation:\n", X.toarray())

Vocabulary: {'from': 12719, 'degroff': 9599, 'netcom': 19118, 'com': 8021, '21012d': 1435, 'subject': 25770, 're': 22452, 'venus': 28288, 'lander': 16593, 'for': 12496, 'conditions': 8345, 'organization': 19968, 'online': 19826, 'communications': 8112, 'services': 24252, '408': 2173, '241': 1619, '9760': 3416, 'login': 17184, 'guest': 13608, 'lines': 17048, 'doubt': 10463, 'there': 26689, 'are': 5013, 'good': 13316, 'prospects': 21857, 'self': 24151, 'armoring': 5066, 'system': 26220, 'surface': 26033, 'several': 24280, 'hundred': 14467, 'degrees': 9598, 'very': 28346, 'high': 14116, 'pressure': 21557, 'of': 19704, 'co2': 7873, 'possibly': 21322, 'sulfuric': 25896, 'and': 4668, 'nitric': 19297, 'acids': 3949, 'or': 19922, 'oxides': 20184, 'but': 6739, 'it': 15677, 'is': 15613, 'notion': 19439, 'to': 26932, 'consider': 8448, 'outer': 20076, 'planets': 21026, 'rs': 23528, 'where': 28943, 'you': 29529, 'might': 18203, 'pick': 20896, 'up': 27931, 'ices': 14591, 'under': 27687, 'less': 1687